name: LuckChat
version: "${project.version}"
api: ["1.0.0"]
author: Zen
main: zen.luckchat.LuckChatPlugin
Softdepend: ["PlaceholderAPI", "Factions", "LuckPerms"]
permissions:
  elementary.open:
    default: true
  elementary.open.list:
    default: true
  elementary.reload:
    default: op
